* Encoding: UTF-8.
GLM Week1 Week2 Week3 Week4 BY Group
  /WSFACTOR=Weeks 4 Polynomial
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Weeks*Group) TYPE=LINE ERRORBAR=NO MEANREFERENCE=NO YAXIS=AUTO
  /PRINT=DESCRIPTIVE
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Weeks
  /DESIGN=Group.
